services:
  servidor:
    build:
      context: .
      dockerfile: Dockerfile
    image: cc7261:pyzmq
    volumes:
      - ./servidor.py:/app/main.py
    ports:
      - 5555:5555
    deploy:
      replicas: 1

  cliente:
    build:
      context: .
      dockerfile: Dockerfile
    image: cc7261:pyzmq
    volumes:
      - ./cliente.py:/app/main.py
    depends_on:
      - servidor
    deploy:
      replicas: 1
